package com.cisco.kta.shct.database.model;


public class aclCommandOutputDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aclcommandoutput.id
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aclcommandoutput.device
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aclcommandoutput.command
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    private String command;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aclcommandoutput.datetime
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    private java.sql.Timestamp datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aclcommandoutput.ouput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    private String ouput;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aclcommandoutput.id
     *
     * @return the value of aclcommandoutput.id
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aclcommandoutput.id
     *
     * @param id the value for aclcommandoutput.id
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aclcommandoutput.device
     *
     * @return the value of aclcommandoutput.device
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aclcommandoutput.device
     *
     * @param device the value for aclcommandoutput.device
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aclcommandoutput.command
     *
     * @return the value of aclcommandoutput.command
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aclcommandoutput.command
     *
     * @param command the value for aclcommandoutput.command
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public void setCommand(String command) {
        this.command = command == null ? null : command.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aclcommandoutput.datetime
     *
     * @return the value of aclcommandoutput.datetime
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public java.sql.Timestamp getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aclcommandoutput.datetime
     *
     * @param datetime the value for aclcommandoutput.datetime
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public void setDatetime(java.sql.Timestamp datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aclcommandoutput.ouput
     *
     * @return the value of aclcommandoutput.ouput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public String getOuput() {
        return ouput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aclcommandoutput.ouput
     *
     * @param ouput the value for aclcommandoutput.ouput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    public void setOuput(String ouput) {
        this.ouput = ouput == null ? null : ouput.trim();
    }
}