package com.cisco.kta.shct.database.model;


public class asr9kCefUsageDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kcefusage.id
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kcefusage.device
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kcefusage.slot
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    private String slot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kcefusage.used
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    private String used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kcefusage.max
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    private String max;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kcefusage.percent
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    private String percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kcefusage.datetime
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    private java.sql.Timestamp datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kcefusage.id
     *
     * @return the value of asr9kcefusage.id
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kcefusage.id
     *
     * @param id the value for asr9kcefusage.id
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kcefusage.device
     *
     * @return the value of asr9kcefusage.device
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kcefusage.device
     *
     * @param device the value for asr9kcefusage.device
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kcefusage.slot
     *
     * @return the value of asr9kcefusage.slot
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public String getSlot() {
        return slot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kcefusage.slot
     *
     * @param slot the value for asr9kcefusage.slot
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public void setSlot(String slot) {
        this.slot = slot == null ? null : slot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kcefusage.used
     *
     * @return the value of asr9kcefusage.used
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public String getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kcefusage.used
     *
     * @param used the value for asr9kcefusage.used
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public void setUsed(String used) {
        this.used = used == null ? null : used.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kcefusage.max
     *
     * @return the value of asr9kcefusage.max
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public String getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kcefusage.max
     *
     * @param max the value for asr9kcefusage.max
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public void setMax(String max) {
        this.max = max == null ? null : max.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kcefusage.percent
     *
     * @return the value of asr9kcefusage.percent
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public String getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kcefusage.percent
     *
     * @param percent the value for asr9kcefusage.percent
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public void setPercent(String percent) {
        this.percent = percent == null ? null : percent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kcefusage.datetime
     *
     * @return the value of asr9kcefusage.datetime
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public java.sql.Timestamp getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kcefusage.datetime
     *
     * @param datetime the value for asr9kcefusage.datetime
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    public void setDatetime(java.sql.Timestamp datetime) {
        this.datetime = datetime;
    }
}