package com.cisco.kta.shct.database.model;


public class asr9kUnicastFloodingDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kunicastflooding.id
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kunicastflooding.device
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kunicastflooding.port
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kunicastflooding.bytes
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    private Integer bytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kunicastflooding.packets
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    private Integer packets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kunicastflooding.avg
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    private Integer avg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asr9kunicastflooding.datetime
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    private java.sql.Timestamp datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kunicastflooding.id
     *
     * @return the value of asr9kunicastflooding.id
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kunicastflooding.id
     *
     * @param id the value for asr9kunicastflooding.id
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kunicastflooding.device
     *
     * @return the value of asr9kunicastflooding.device
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kunicastflooding.device
     *
     * @param device the value for asr9kunicastflooding.device
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kunicastflooding.port
     *
     * @return the value of asr9kunicastflooding.port
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kunicastflooding.port
     *
     * @param port the value for asr9kunicastflooding.port
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kunicastflooding.bytes
     *
     * @return the value of asr9kunicastflooding.bytes
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public Integer getBytes() {
        return bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kunicastflooding.bytes
     *
     * @param bytes the value for asr9kunicastflooding.bytes
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public void setBytes(Integer bytes) {
        this.bytes = bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kunicastflooding.packets
     *
     * @return the value of asr9kunicastflooding.packets
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public Integer getPackets() {
        return packets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kunicastflooding.packets
     *
     * @param packets the value for asr9kunicastflooding.packets
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public void setPackets(Integer packets) {
        this.packets = packets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kunicastflooding.avg
     *
     * @return the value of asr9kunicastflooding.avg
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public Integer getAvg() {
        return avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kunicastflooding.avg
     *
     * @param avg the value for asr9kunicastflooding.avg
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public void setAvg(Integer avg) {
        this.avg = avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asr9kunicastflooding.datetime
     *
     * @return the value of asr9kunicastflooding.datetime
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public java.sql.Timestamp getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asr9kunicastflooding.datetime
     *
     * @param datetime the value for asr9kunicastflooding.datetime
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    public void setDatetime(java.sql.Timestamp datetime) {
        this.datetime = datetime;
    }
}