package com.cisco.kta.shct.database.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cisco.kta.shct.database.model.asr9kUnicastFloodingDto;

public interface asr9kUnicastFloodingDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int insert(asr9kUnicastFloodingDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int insertSelective(asr9kUnicastFloodingDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    
    List<asr9kUnicastFloodingDto> selectAllToday();
    
    List<asr9kUnicastFloodingDto> selectByDeviceByDate(@Param("device")String device, @Param("date")String date);
    
    List<asr9kUnicastFloodingDto> selectByDeviceByPort(@Param("device")String device, @Param("port")String port);
    
    List<asr9kUnicastFloodingDto> selectAllByDate(@Param("date")String date);
    
    asr9kUnicastFloodingDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int updateByPrimaryKeySelective(asr9kUnicastFloodingDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int updateByPrimaryKey(asr9kUnicastFloodingDto record);
}