package com.cisco.kta.shct.database.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cisco.kta.shct.database.model.asr9kCefUsageDto;

public interface asr9kCefUsageDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kcefusage
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kcefusage
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    int insert(asr9kCefUsageDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kcefusage
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    int insertSelective(asr9kCefUsageDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kcefusage
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
      
    List<asr9kCefUsageDto> selectAll();
    
    List<asr9kCefUsageDto> selectAllByDesc();
    
    List<asr9kCefUsageDto> selectBySlot(@Param("device")String device, @Param("slot")String slot);
    
    asr9kCefUsageDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kcefusage
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    int updateByPrimaryKeySelective(asr9kCefUsageDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kcefusage
     *
     * @mbggenerated Fri Mar 18 15:03:21 CST 2016
     */
    int updateByPrimaryKey(asr9kCefUsageDto record);
}