package com.cisco.kta.shct.database.dao;

import com.cisco.kta.shct.database.model.aclCommandOutputDto;

public interface aclCommandOutputDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aclcommandoutput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aclcommandoutput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    int insert(aclCommandOutputDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aclcommandoutput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    int insertSelective(aclCommandOutputDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aclcommandoutput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    aclCommandOutputDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aclcommandoutput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    int updateByPrimaryKeySelective(aclCommandOutputDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aclcommandoutput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(aclCommandOutputDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aclcommandoutput
     *
     * @mbggenerated Wed Apr 13 12:45:27 CST 2016
     */
    int updateByPrimaryKey(aclCommandOutputDto record);
}