package com.cisco.kta.shct.database.dao;

import com.cisco.kta.shct.database.model.asr9kUnicastFloodingDto;

public interface asr9kUnicastFloodingDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int insert(asr9kUnicastFloodingDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int insertSelective(asr9kUnicastFloodingDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    asr9kUnicastFloodingDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int updateByPrimaryKeySelective(asr9kUnicastFloodingDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asr9kunicastflooding
     *
     * @mbggenerated Tue Apr 26 18:13:18 CST 2016
     */
    int updateByPrimaryKey(asr9kUnicastFloodingDto record);
}